shopping/models.py
import uuid
from jdatetime import datetime
from app import db
from sqlalchemy import Column, ForeignKey, Text, Integer, String, Boolean, DateTime, event, Table, DECIMAL
from auth.models import User
from flask_login import current_user



carts_products = Table('carts_products', db.metadata,
    Column('cart_id', Integer, ForeignKey('shopping_cart.id', ondelete='cascade')),
    Column('product_id', Integer, ForeignKey('shopping_products.id', ondelete='cascade'))
)


class Cart(db.Model):
    __tablename__  = 'shopping_cart'
    id = Column(Integer(), primary_key=True)
    user_id = Column(Integer(), ForeignKey('users.id'))
    products = db.relationship('Product', secondary=carts_products, back_populates='carts')
    sum_price = Column(String(150), default='0')
    created_at = Column(DateTime(), default=datetime.now())
    updated_at = Column(DateTime(), default=datetime.now())
    serial = Column(String(100))
    transaction = Column(Boolean(), default=False)

    def __init__(self):
        self.serial = str(uuid.uuid5(uuid.NAMESPACE_DNS, f'{current_user.name + str(datetime.now())}'))
        
    def __repr__(self) -> str:
        return self.products
    
    def user(self):
        return User.query.get(self.user_id).name
    
    def get_products(self):
        return [product.name for product in self.products ]


        
    



class Product(db.Model):
    __tablename__ = 'shopping_products'
    id = Column(Integer(), primary_key=True)
    name = Column(String(100), nullable=False, unique=True)
    price = Column(Integer(), default=0)
    category_id = Column(Integer(), ForeignKey('shopping_categories.id', ondelete='cascade'))
    number = Column(Integer(), default=0)
    image = Column(String(100), default='img/product.jpg')
    date = Column(DateTime(), default=datetime.now())
    rating = Column(db.DECIMAL(8, 2), default=1.0)
    carts = db.relationship('Cart', secondary=carts_products, back_populates='products')
    sold_number = Column(Integer(), default=0)
    
    def __repr__(self) -> str:
        return self.name
    
    def is_available(self):
        return True if len(self.number) > 0 else False 
    
    def getCategory(self, category_id):
        return Category.query.get(category_id).title
    



class Category(db.Model):
    __tablename__ = 'shopping_categories'
    id = Column(Integer(), primary_key=True)    
    title = Column(String(100), nullable=False, unique=True)
    date = Column(DateTime(), default=datetime.now())
    products = db.relationship('Product', backref='category')

    def __repr__(self) -> str:
        return self.title
        



class Order(db.Model):
    __tablename__ = 'shopping_orders'
    id = Column(Integer(), primary_key=True)
    user_id = Column(Integer(), ForeignKey('users.id'))
    product_id = Column(Integer(), ForeignKey('shopping_products.id'))
    number = Column(Integer(), default=1)
    bought = Column(Boolean(), default=False)
    date = Column(DateTime(), default=datetime.now())
    serial = Column(String(120))

    def __repr__(self) -> str:
        return super().__repr__()
    
    def get_price(self):
        return Product.query.get(self.product_id).price
    
    def get_product_name(self):
        return Product.query.get(self.product_id).name
    
    def get_category_name(self, category_id):
        category_id =  Product.query.get(self.product_id).category_id
        return Category.query.get_or_404(category_id).title
    
    def get_product_image(self):
        return Product.query.get(self.product_id).image
    

    

shopping/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Length
from wtforms import StringField, FileField, SelectField, IntegerField, ValidationError
from .models import Category, Product
from flask import flash

class ProductForm(FlaskForm):
    name = StringField('Product Name')
    price = StringField('Price', validators=[Length(min=0)])
    # category = SelectField('Category', choices=[(index+1, cat) for index,cat in enumerate(Category.query.all())])
    category = SelectField('Category', choices=[(cat.id, cat.title) for cat in Category.query.all()])
    number = StringField('Number', validators=[Length(min=0)])
    image = FileField('Image')
    rating = StringField('Rating', validators=[Length(min=0, max=5)])
    # role = SelectField('Role', choices=[('3', 'کاربر عادی '), ('1', 'کاربر درجه 1'), ('2', 'کاربر درجه 2'), ('0', 'کاربر ادمین')])



class CategoryForm(FlaskForm):
    title = StringField('Category Name')


class UserInfoForm(FlaskForm):
    phone = StringField('Phone', validators=[DataRequired(), Length(min=11, max=11)])
    province = StringField('Province')
    city = StringField('City')
    street = StringField('Street')
    post_code = StringField('Post Code', validators=[DataRequired(), Length(min=10, max=10)])

    def validate_phone(form, field):
        if len(field.data) != 11:
            flash('your mobile number is incorrect, please try again', 'warning')
            raise ValidationError('شماره همراه نامعتبر است')
        
    def validate_post_code(form, field):
        if len(field.data) != 10:
            raise ValidationError('کد پستی غیرمعتبر است')

shopping/__init__.py
from flask import Blueprint


shopping = Blueprint('shopping', __name__ , url_prefix='/shopping/')


from . import views

shopping/views.py
import os
import jdatetime
import random
import uuid
from flask import redirect, url_for, render_template, flash, request, session
from flask_login import login_required, current_user
from app import db, app
from . import shopping
from auth.models import User
from .models import Product, Category, Cart, Order
from .forms import ProductForm, CategoryForm, UserInfoForm
from werkzeug.utils import secure_filename
from utils import save_image, allow_extension
from sqlalchemy.exc import IntegrityError
from sqlalchemy import desc






@shopping.route('', methods=['POST', 'GET'])
def index():
    page = request.args.get('page', default=1, type=int)
    products = Product.query.order_by(desc(Product.date)).paginate(page=page, per_page=10)
    orders = Order.query.filter_by(user_id=current_user.id, bought=0).all()
    order_product = [order.product_id for order in orders]
    # ============ set global variable, but dont work in app.py =======
    # orders = Order.query.filter_by(user_id=current_user.id).all()
    app.jinja_env.globals['orders'] = orders
    # ==================================================================
    return render_template('shopping/index.html', products=products, order_product=order_product) 


@shopping.route('create-category', methods=['POST', 'GET'])
def category_create():
    form = CategoryForm()
    categories = Category.query.order_by(desc(Category.date)).all()
    if request.method == "POST":
        if form.validate_on_submit():
            cat = Category()
            cat.title = request.form.get('title')
            try:
                db.session.add(cat)
                db.session.commit()
                flash('your data is saved successfully', 'success')
            except IntegrityError as er:
                db.session.rollback()
                flash(f'error {er} is happened, please try again', 'warning')
            finally:
                return redirect(url_for('shopping.category_create', form=form))
        
        flash('form is not valid', 'warning')

    return render_template('shopping/category-create.html', form=form, categories=categories)


@shopping.route('edit-category/<int:cat_id>', methods=['POST', 'GET'])
def category_edit(cat_id):
    categories = Category.query.all()
    category = Category.query.get(cat_id)
    form = CategoryForm()
    if request.method == 'POST':
        title = request.form.get('title')
        category.title = title
        try:
            db.session.add(category)
            db.session.commit()
        except IntegrityError as ie:
            db.session.rollback()
            flash(f'error {ie} is happened', 'warning')
        except Exception as e:
            flash(f'error {e} is happened, please try again !!', 'warning')
        finally:
            return redirect(url_for('shopping.category_edit', categories=categories, title=category.title, cat_id=category.id, form=form))

    return render_template('shopping/category-edit.html', categories=categories, title=category.title, cat_id=category.id, form=form)

@shopping.route('/new-product', methods=['POST', 'GET'])
def product_new():
    print(jdatetime.date.today())
    form = ProductForm()
    if request.method == 'POST': 
        if form.validate_on_submit():
            old_product = Product.query.filter_by(name=request.form.get('name')).first()
            if old_product or request.form.get('name') == '':
                flash('this Name for product is registered previously, please select another name', 'warning')
                return redirect(url_for('shopping.product_new', form=form))
            product = Product()
            product.name = request.form.get('name')
            product.price = request.form.get('price')
            product.category_id = request.form.get('category')
            product.number = request.form.get('number')
            product.rating = request.form.get('rating')
            image = request.files.get('image')
            today = str(jdatetime.date.today())
            if save_image(image, 'shopping', 'shopping.product_new', form):
                product.image = f"uploads/shopping/{today}/{image.filename}"

            try:
                db.session.add(product)
                db.session.commit()
                flash(f'product {product.name} is registered successfully', 'success')
            except IntegrityError as er:
                db.session.rollback()
                flash(f'error {er} is happened', 'warning')
                raise er
            except Exception as e:
                    # Raise all other exceptions. 
                    flash(f'error {e} is happened', 'warning')
                    raise e
            finally:
                return redirect(url_for('shopping.product_new', form=form))

        flash('form is not validate', 'warning')

    return render_template('shopping/product-new.html', form=form)


@shopping.route('/products-list', methods=['POST', 'GET'])
def products_list():
    page = request.args.get('page', default=1, type=int)
    products = Product.query.order_by(desc(Product.date)).paginate(page=page, per_page=4)

    return render_template('shopping/products-list.html', products=products) 


@shopping.route('/product-detail/<int:product_id>', methods=['POST', 'GET'])
def product_detail(product_id):
    print('==================================================================================')
    print('request url is ---> ', request.url)
    print('request url is ---> ', request.base_url, request.host_url, request.root_url)
    # print('request json', request.json)
    print('request blueprint ---> ', request.blueprint)
    print('request cookies ---> ', request.cookies)
    print('request date ---> ', request.date)
    print('request headers ---> ', request.headers)
    print('request user_agent ---> ', request.user_agent)
    print('request args ---> ', request.args)
    print('request values ---> ', request.values)
    print('request scheme ---> ', request.scheme)
    print('request remote_addr ---> ', request.remote_addr)
    print('request path ---> ', request.path)
    # print('request module', request.module)
    print('request headers ---> ', request.headers)
    print('request full_path ---> ', request.full_path)
    print('request endpoint ---> ', request.endpoint)
    print('request access_route ---> ', request.access_route)
    print('request environ ---> ', request.environ)
    print('request environ(REMOTE_ADDR) ---> ', request.environ['REMOTE_ADDR'])
    print('==================================================================================')
    product = Product.query.get(product_id)
    orders = Order.query.filter_by(user_id=current_user.id).all()
    order_product = [order.product_id for order in orders]
    

    return render_template('shopping/product-detail.html', product=product, order_product=order_product)


@shopping.route('edit-product/<int:product_id>', methods=['POST', 'GET'])
def product_edit(product_id):
    form = ProductForm()
    product = Product.query.filter_by(id=product_id).first()
    form.category.default = product.category_id
    form.process()
    if request.method == 'POST':
        form = ProductForm()
        if form.validate_on_submit():
            product.name = request.form.get('name')
            product.price = request.form.get('price')
            product.number = request.form.get('number')
            product.rating = request.form.get('rating')
            product.category_id = request.form.get('category')
            # ===========================_Image_Upload_=================================
            image = request.files.get('image')
            today = str(jdatetime.date.today())
            if image.filename is None:
                flash('you not select an image properly', 'warning')
            if image:
                file_secure = secure_filename(image.filename)
                if not allow_extension(file_secure):
                    flash('the extension of image is not allowed, please try again', 'warning')
                    return redirect(url_for('shopping.product_edit', product_id=product.id, form=form))
                folder = os.path.join(app.config['UPLOAD_DIR'], 'shopping', str(today))
                try:
                    os.makedirs(folder)
                except:
                    pass
                finally:
                    image.save(os.path.join(folder, file_secure))
                    product.image = f"uploads/shopping/{today}/{image.filename}"
            # =============================_End_Of_Image_Upload_===========================
            try:
                db.session.commit()
                flash(f'your product {product.name} is editted successfully', 'success')
            except IntegrityError as er:
                db.session.rollback()
                flash(f'error {er} is happened', 'warning')
            except Exception as e:
                flash(f'error {e} is happened, please try again', 'warning')
            finally:
                return redirect(url_for('shopping.product_edit', product_id=product.id, form=form))
        else:
            flash('your form is not validate, please try again', 'warning')

    return render_template('shopping/product-edit.html', product=product, form=form)


@shopping.route('product/buy/<int:product_id>', methods=['POST', 'GET'])
def product_buy(product_id):
    print(request.endpoint)
    product = Product.query.get(product_id)
    if request.method == 'POST':
        order = Order()
        order.user_id = current_user.id 
        order.product_id = product.id
        order.number = int(request.form.get('number')) if request.form.get('number') != '' else 1
        if order.number > 5 :
            flash('you dont select product more than 5, please decreese your number of product', 'warning')
            if request.args.get('page') == 'product_detail':
                return redirect(url_for('shopping.product_detail', product_id=product.id))

templates/shopping/best-seller-list.html
{% extends 'admin/index.html' %}

{% block title %} لیست پرفروش ترین محصولات {% endblock %}

{% block admin_content %}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title"> لیست پرفروش ترین محصولات </h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example1_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-4 col-md-4">
                                <div class="input-group dataTables_filter">
                                    <input type="search" class="form-control form-control-sm" placeholder="جستجو در جدول" aria-label="Search"
                                     aria-describedby="search-addon" />
                                    <button id="search-button" type="button" class="btn btn-primary">
                                        <i class="fa fa-search"></i>
                                      </button>
                                </div>
                            </div>                    
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example1" class="table table-bordered table-striped mt-2">
                                    <thead>
                                        <tr class="text-center">
                                            <th> ردیف </th>
                                            <th> نام </th>
                                            <th> دسته بندی </th>
                                            <th> قیمت(تومان) </th>
                                            <th> تعداد فروش </th>
                                            <th>موجودی انبار</th>
                                            <th> تاریخ ایجاد </th>
                                            <th> محبوبیت </th>
                                            <th>عملیات</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for product in products.items %}
                                        <tr class="text-center">
                                            <td>{{loop.index}}</td>
                                            <td><a href="{{url_for('shopping.product_detail', product_id=product.id)}}">{{product.name}}</a></td>
                                            <td>{{product.getCategory(product.category_id)}}</td>
                                            <td>{{'{0:,}'.format(product.price | int)}}</td>
                                            <td>{{product.sold_number}}</td>
                                            <td>{{product.number}}</td>
                                            <td>{{product.date.strftime('%Y-%m-%d')}}</td>
                                            <td>
                                                <span class="progress mb-3"> 
                                                    <div class="progress-bar bg-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: {{(product.rating)*20}}%">
                                                        <span class="sr-only">۲۰% Complete</span>
                                                    </div>
                                                </span>
                                            </td>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="#"
                                                        class="btn btn-sm btn-warning"><span class="fa fa-pencil"></span></a>
                                                    
                                                    <a href="#"
                                                        class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
                                                    
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <div class="row">
                                    <div class="col-sm-12 col-md-5"></div>
                                    <div class="col-sm-12 col-md-7">
                                        <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                            <ul class="pagination">
                                                {% if products.has_prev %}
                                                <li class="paginate_button page-item previous" id="example1_previous">
                                                    <a href="{{url_for('shopping.products_list', page=products.prev_num)}}"
                                                     aria-controls="example1" data-dt-idx="0" tabindex="0" class="page-link">قبلی</a>
                                                </li>
                                                {% endif %}
                                                {% for page_number in products.iter_pages() %}
                                                    {% if page_number %}
                                                        <li class="paginate_button page-item">
                                                            <a href="{{url_for('shopping.products_list', page=page_number)}}"
                                                                aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                                                            {{page_number}}
                                                            </a>
                                                        </li>
                                                    {% else %}
                                                        <li class="paginate_button page-item">
                                                            <a href="#"
                                                                aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                                                            {{page_number}}
                                                            </a>
                                                        </li>
                                                    {% endif %}
                                                {% endfor %}
                                                {% if products.has_next %}
                                                <li class="paginate_button page-item next" id="example1_next">
                                                    <a href="{{url_for('shopping.products_list', page=products.next_num)}}"
                                                        aria-controls="example1" data-dt-idx="7" tabindex="0"
                                                        class="page-link">بعدی</a>
                                                </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                <!-- /.card-body -->

            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->


{% endblock %}

templates/shopping/index.html
{% extends 'admin/index.html' %}

{% block title %} لیست محصولات {% endblock %}

{% block admin_content %}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title"> لیست محصولات </h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example1_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-4 col-md-4">
                                <div class="input-group dataTables_filter mb-5">
                                    <input type="search" class="form-control form-control-sm" placeholder="جستجو در جدول" aria-label="Search"
                                     aria-describedby="search-addon" />
                                    <button id="search-button" type="button" class="btn btn-primary">
                                        <i class="fa fa-search"></i>
                                      </button>
                                </div>
                            </div>  
                            <div class="col-sm-4"></div>   
                            <div class="col-sm-4">
                                <a href="{{url_for('shopping.buy_end')}}" 
                                class="btn btn-info float-left {% if orders|length < 1 %} disabled {% endif %}"> لیست محصولات خریداری شده </a>
                            </div>         
                        </div>
                        <div class="row">
                            {% for product in products.items %}
                            <div class="card col-md-3" style="width: 18rem;">
                                <img class="card-img-top" src="{{url_for('static', filename=product.image)}}" height="250" alt="Card image cap">
                                <div class="card-body text-center">
                                    <a href="{{url_for('shopping.product_detail', product_id=product.id)}}"> <h5 class="card-title"> {{product.name}} </h5> </a>
                                    <p class="card-text"><span>{{product.price}}</span><span class="mr-1">تومان</span></p>
                                    {% if product.id in order_product %} 
                                    <a href="{{url_for('shopping.product_buy', product_id=product.id)}}" class="btn btn-warning"> حذف محصول از سبد خرید </a>
                                    {% else %}
                                    <form class="form-inline row" action="{{url_for('shopping.product_buy', product_id=product.id)}}" method="post">
                                        <div class="form-group">
                                            <input type="number" name="number" value="1" class="form-control", placeholder="تعداد">
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary btn-block mr-1">خرید</button>
                                        </div>
                                    </form>
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-5"></div>
                            <div class="col-sm-12 col-md-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                    <ul class="pagination">
                                        {% if products.has_prev %}
                                        <li class="paginate_button page-item previous disabled" id="example1_previous">
                                            <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0"
                                                class="page-link">قبلی</a>
                                        </li>
                                        {% endif %}
                                        {% for page_number in products.iter_pages() %}
                                            {% if page_number %}
                                                <li class="paginate_button page-item">
                                                    <a href="{{url_for('shopping.products_list', page=page_number)}}"
                                                        aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                                                    {{page_number}}
                                                    </a>
                                                </li>
                                            {% else %}
                                                <li class="paginate_button page-item">
                                                    <a href="#"
                                                        aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                                                    {{page_number}}
                                                    </a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if products.has_next %}
                                        <li class="paginate_button page-item next" id="example1_next">
                                            <a href="{{url_for('shopping.products_list', page=products.next_num)}}"
                                                aria-controls="example1" data-dt-idx="7" tabindex="0"
                                                class="page-link">بعدی</a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                <!-- /.card-body -->

            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->


{% endblock %}

templates/shopping/test.html
<div class="row">
    <div class="col-sm-12 col-md-5"></div>
    <div class="col-sm-12 col-md-7">
        <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
            <ul class="pagination">
                {% if posts.has_prev %}
                <li class="paginate_button page-item previous disabled" id="example1_previous">
                    <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0"
                        class="page-link">قبلی</a>
                </li>
                {% endif %}
                {% for page_number in posts.iter_pages() %}
                    {% if page_number %}
                        <li class="paginate_button page-item">
                            <a href="{{url_for('blog.posts', page=page_number)}}"
                                aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                            {{page_number}}
                            </a>
                        </li>
                    {% else %}
                        <li class="paginate_button page-item">
                            <a href="#"
                                aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                            {{page_number}}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                <li class="paginate_button page-item next" id="example1_next">
                    <a href="{{url_for('blog.posts', page=posts.next_num)}}"
                        aria-controls="example1" data-dt-idx="7" tabindex="0"
                        class="page-link">بعدی</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>