blog/models.py
from jdatetime import datetime
from app import db
from sqlalchemy import Column, ForeignKey, Text, Integer, String, Boolean, DateTime, event, Table
from auth.models import User
from slugify import slugify





# post_like = Table('posts-likes', db.metadata,
#     Column('post_id', Integer(), ForeignKey('posts.id', ondelete='cascade')),
#     Column('user_id', Integer(), ForeignKey('users.id', ondelete='cascade'))
#     )




class Post(db.Model):
    __tablename__ = 'posts'
    id = Column(Integer(), primary_key=True)
    title = Column(String(100), nullable=False, unique=True)
    slug = Column(String(100), nullable=False)
    content = Column(Text(), nullable=False)
    image = Column(String(100), nullable=False)
    publish = Column(Boolean(), default=True)
    user_id = Column(Integer(), ForeignKey('users.id'))
    views = Column(Integer(), default=0)
    created_at = Column(DateTime(), default=datetime.now())
    updated_at = Column(DateTime(), default=datetime.now())
    # user_like_id = db.relationship('User', secondary=post_like, back_populates='posts')
    # likes = Column(Integer(), ForeignKey('postlikes.id'))
    # likes = db.relationship('PostLikes', backref='post', lazy='dynamic')
    likes = db.relationship('PostLikes', backref='post')
    comments = db.relationship('Comment', backref='post')

    def __repr__(self):
        return f'{self.title} as {self.user_id}'

    def getWriter(self, id):
        return User.query.get(id).name

    @staticmethod
    def generate_slug(cls, value, oldvalue, initiator):
        if value and (not cls.slug and value != oldvalue):
            cls.slug = slugify(value, allow_unicode=True)



class Comment(db.Model):
    __tablename__ = 'comments'
    id = Column(Integer(), primary_key=True)
    body = Column(String(200), nullable=False)
    publish = Column(Boolean(), default=False)
    created_at = Column(DateTime(), default=datetime.now())
    post_id = Column(Integer(), ForeignKey('posts.id'))
    user_id = Column(Integer(), ForeignKey('users.id'))
    replies = db.relationship('Reply', backref='comment')

    def __repr__(self):
        return f'comment {self.body[:20]} for {self.post_id}'

    def getWriter(self, id):
        return User.query.get(id).name

    def getWriterAvatar(self, id):
            return User.query.get(id).avatar




class Reply(db.Model):
    __tablename__ = 'replies'
    id = Column(Integer(), primary_key=True)
    body = Column(String(200), nullable=False)
    publish = Column(Boolean(), default=False)
    created_at = Column(DateTime(), default=datetime.now())
    comment_id = Column(Integer(), ForeignKey('comments.id'))
    user_id = Column(Integer(), ForeignKey('users.id'))

    def __repr__(self):
        return f'reply {self.id} for comment {self.comment_id} by {self.user_id}'

    def getWriter(self, id):
        return User.query.get(id).name

    def getWriterAvatar(self, id):
            return User.query.get(id).avatar




class PostLikes(db.Model): # when a user like a post
    __tablename__ = 'postlikes'
    id = Column(Integer(), primary_key=True)
    created_at = Column(DateTime(), default=datetime.now())
    post_id = Column(Integer(), ForeignKey('posts.id'))
    user_id = Column(Integer(), ForeignKey('users.id'))

    def __repr__(self):
        return f'user {self.user_id} likes post{self.post_id}'

    def get_user_id(self):
        return self.user_id
        







db.event.listen(Post.title, 'set', Post.generate_slug, retval=False)

blog/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, EqualTo, Length, Email
from wtforms import PasswordField, StringField, EmailField, SelectField, FileField, TextAreaField, BooleanField
from flask_ckeditor import CKEditorField




class PostCreateForm(FlaskForm):
    title = StringField('Title')
    content = CKEditorField('Content')
    image = FileField('Image')
    publish = BooleanField('Publish', default=0)



class CommentForm(FlaskForm):
    body = StringField('Comment', validators=[DataRequired()])

blog/__init__.py
from flask import Blueprint



blog = Blueprint('blog', __name__, url_prefix='/blog/')


from . import views

blog/views.py
import os
import jdatetime
import json
from flask import redirect, url_for, render_template, flash, request
from flask_login import login_required, current_user
from app import db, app
from . import blog
from auth.models import User
from .forms import PostCreateForm, CommentForm
from .models import Post, Comment, PostLikes, Reply
from werkzeug.utils import secure_filename
from utils import allow_extension
from sqlalchemy.exc import IntegrityError
from sqlalchemy import desc






@blog.route('post-create', methods=['POST', 'GET'])
@login_required
def post_create():
    form = PostCreateForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            new_post = Post()
            new_post.title = request.form.get('title')
            new_post.content = request.form.get('content')
            new_post.publish = 1 if request.form.get('publish') == 'y' else 0
            new_post.user_id = current_user.id
            print('image is ',request.files.get('image'))
            image = request.files.get('image')
            if image.filename == '':
                flash('image file is not selected properly', 'warning')
                return redirect(url_for('blog.post_create', form=form))
            if image:
                filename = image.filename
                file_secure = secure_filename(filename)
                if not allow_extension(file_secure):
                    flash('this extension for image file is not allowed', 'warning')
                    return redirect(url_for('blog.post_create', form=form))
                today = jdatetime.date.today()
                folder = os.path.join(app.config['UPLOAD_DIR'], 'blog', f'{today}')
                try:
                    os.makedirs(folder)
                except:
                    pass
                file = os.path.join(folder, file_secure)
                image.save(file)
                new_post.image = f'uploads/blog/{today}/{filename}'
            try:
                db.session.add(new_post)
                db.session.commit()
                flash(f'the Post {new_post.title} is created successfully', 'success')
                return redirect(url_for('blog.post_create', form=form))
            except IntegrityError():
                db.session.rollback()
                flash(IntegrityError, 'error')
                return redirect(url_for('blog.post_create', form=form))
            
    return render_template('blog/post-create.html', form=form)



@blog.route('posts', methods=['POST', 'GET'])
def posts():
    # posts = Post.query.all()
    page = request.args.get('page', default=1, type=int)
    # posts = Post.query.order_by(desc(Post.created_at)).paginate(page=page, per_page=4)
    posts = Post.query.order_by(Post.id.desc()).paginate(page=page, per_page=4)
    
    return render_template('blog/posts.html', posts=posts)



@blog.route('post-publish/<int:post_id>', methods=['GET']) # TODO this function must be ajax
@login_required
def post_publish(post_id):
    post = Post.query.filter_by(id=post_id).first()
    post.publish = not(post.publish)
    db.session.add(post)
    db.session.commit()
    return redirect(url_for('blog.posts'))



@blog.route('post-edit/<int:post_id>', methods=['POST', 'GET'])
@login_required
def post_edit(post_id):
    form = PostCreateForm()
    post = Post.query.filter_by(id=post_id).first()
    form.content.data = post.content
    if request.method == 'POST':
        post.title = request.form.get('title')
        post.content = request.form.get('content')
        post.publish = 1 if request.form.get('publish') == 'y' else 0
        image = request.files.get('image')
        print('image is : ', image)
        if image.filename == '':
            flash('your image is not modified properly', 'warning')
        else:
            filename = image.filename
            file_secure = secure_filename(filename)
            if not allow_extension(file_secure):
                flash('this extension for image file is not allowed', 'warning')
                return redirect(url_for('blog.post_create', form=form))
            folder = os.path.join(app.config['UPLOAD_DIR'], 'blog', f'{jdatetime.date.today()}')
            try:
                os.makedirs(folder)
            except:
                pass
            file = os.path.join(folder, file_secure)
            image.save(file)
            post.image = f'uploads/blog/{jdatetime.date.today()}/{filename}'
        try:
            db.session.add(post)
            db.session.commit()
            flash(f'the Post {post.title} is modified successfully', 'success')
            return redirect(url_for('blog.posts'))
        except IntegrityError():
            db.session.rollback()
            flash(IntegrityError, 'error')
            return redirect(url_for('blog.post_edit', form=form, post=post))
        
    return render_template('/blog/post_edit.html', form=form, post=post)



@blog.route('post-detail/<int:post_id>', methods=['POST', 'GET'])
@login_required
def post_detail(post_id):
    comment_form = CommentForm()
    post = Post.query.filter_by(id=post_id).first()
    post.views += 1
    db.session.add(post)
    db.session.commit()
    # comments = Comment.query.filter_by(post_id=post_id).all()
    comments = post.comments

    return render_template('/blog/post-detail.html', post=post, comments=comments, comment_form=comment_form)



@blog.route('post-writer/<int:user_id>', methods=['POST', 'GET'])
@login_required
def post_writer(user_id):
    post_user = Post.query.filter_by(user_id=user_id).all()
    # user = post_user[0].getWriter(user_id)
    user = User.query.filter_by(id=user_id).first()
    comment_form = CommentForm()

    return render_template('/blog/post-writer.html', post_user=post_user, user=user, comment_form=comment_form)



@blog.route('post-delete/<int:post_id>', methods=['GET'])
@login_required
def post_delete(post_id):
    Post.query.filter_by(id=post_id).delete()
    db.session.commit()

    return redirect(url_for('blog.posts'))




@blog.route('comment-send/<int:post_id>', methods=['POST', 'GET'])
@login_required
def comment_send(post_id):
    comment_form = CommentForm()

    comment = Comment()
    comment.body = request.form.get('body')
    comment.post_id = post_id
    comment.user_id = current_user.id

    try:
        db.session.add(comment)
        db.session.commit()
        flash('your comment is sent successfully', 'success')
        return redirect(url_for('blog.post_detail', post_id=post_id, comment_form=comment_form))
    except IntegrityError:
        db.session.rollback()
        flash(IntegrityError, 'danger')
        flash('your comment not sent properly', 'warning')
        return redirect(url_for('blog.post_detail', post_id=post_id, comment_form=comment_form))



@blog.route('reply-comment/<int:post_id>/<int:comment_id>', methods=['POST'])
@login_required
def reply_comment(post_id, comment_id):
    new_reply = Reply()
    new_reply.body = request.form.get('reply')
    new_reply.comment_id = comment_id
    new_reply.user_id = current_user.id
    db.session.add(new_reply)
    db.session.commit()
    return redirect(url_for('blog.post_detail', post_id=post_id))



@blog.route('post-like/<int:post_id>/<int:user_id>', methods=['POST', 'GET'])
@login_required
def post_like(post_id, user_id):
    user_liked = PostLikes.query.filter_by(user_id=user_id, post_id=post_id).first()
    # dislike
    if user_liked: 
        PostLikes.query.filter_by(post_id=post_id, user_id=user_id).delete()
        db.session.commit()
        return redirect(url_for('blog.post_detail', post_id=post_id))

    post_like = PostLikes()
    post_like.user_id = user_id
    post_like.post_id = post_id
    # post = Post.query.get_or_404(post_id)
    # user = User.query.get_or_404(user_id)
    try:
        db.session.add(post_like)
        db.session.commit()
        # flash(f'you {user.name} likes post {post.title}.', 'info')
        return redirect(url_for('blog.post_detail', post_id=post_id))
    except IntegrityError:
        db.session.rollback()
        # flash(f'your like not saved properly', 'warning')
        return redirect(url_for('blog.post_detail', post_id=post_id))




# ajax request
@blog.route('ajax-post', methods=['POST', 'GET'])
@login_required
def ajax_post():
    flash('you are clicked the ajax button', 'warning')
    return json.dumps({'status':'OK'});

templates/blog/post-create.html
{% extends 'admin/index.html' %}

{% block title %} ثبت خبر جدید {% endblock %}

{% block admin_content %}

<div class="offset-md-2 col-md-8">
    <div class="card card-success">

        <div class="card-header">
            <h3 class="card-title"> خبر جدید </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{url_for('blog.post_create')}}" method="post" novalidate  enctype="multipart/form-data">

            {{form.csrf_token}}

            <div class="card-body">
                <div class="form-group">
                    <label for="exampleInputEmail1"> عنوان خبر </label>
                    {{form.title(class='form-control')}}
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1"> محتوای خبر </label>
                    {{form.content(class='form-control')}}
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">ارسال عکس </label>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" name="image" class="custom-file-input" id="exampleInputFile">
                            <label class="custom-file-label" for="exampleInputFile">انتخاب عکس</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text" id="">Upload</span>
                        </div>
                    </div>
                </div>
                <div class="form-check">
                    {{form.publish(class='form-check-input')}}
                    <label class="form-check-label" for="exampleCheck1"> منتشر شود؟ </label>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">ایجاد</button>
            </div>
        </form>
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='content') }}
    </div>
</div>

{% endblock %}

templates/blog/post-detail.html
{% extends 'admin/index.html' %}

{% block title %} خبر | {{post.title}} {% endblock %}

{% block admin_content %}

{{ super() }}
{{ ckeditor.load() }}

<div class="offset-md-2 col-md-8">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{post.title}}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left text-sm">
                        <li class="breadcrumb-item"><a href="{{url_for('blog.posts')}}">اخبار</a></li>
                        <li class="breadcrumb-item active">{{post.title}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="card card-widget">
        <div class="card-header">
            <div class="user-block">
                <img class="img-circle" src="{{url_for('static', filename='img/user4-128x128.jpg')}}" alt="User Image">
                <span class="username"><a href="{{url_for('blog.post_writer', user_id=post.user_id)}}">{{post.getWriter(post.user_id)}}</a></span>
                <span class="description">{{ moment(post.updated_at).fromNow() }} به اشتراک گذاشته شد</span>
            </div>
            <!-- /.user-block -->
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-toggle="tooltip" title=""
                    data-original-title="Mark as read">
                    <i class="fa fa-circle-o"></i></button>
                <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i>
                </button>
            </div>
            <!-- /.card-tools -->
        </div>
        <!-- /.card-header -->
        <div class="card-body">
           
            <img class="img-fluid pad mr-auto" src="{{url_for('static', filename=post.image)}}">
            <!-- <p class="card-body">{{post.content}}</p> -->
            <div class="mb-5"> {{post.contnet}} </div>
            {{ super() }}
            {{ckeditor.load()}}
            <br>
            <button type="button" class="btn btn-default btn-sm"><i class="fa fa-share"></i> اشتراک گذاری</button>
            <a href="{{url_for('blog.post_like', post_id=post.id, user_id=current_user.id)}}" class="btn btn-default btn-sm">
            <!-- likes and dislikes button -->
            {% set ns = namespace(liked=false) %}
            {% for post in post.likes %} 
                {% if current_user.id == (post.get_user_id() | int) %}  
                {% set ns.liked = True %}
                {% endif %} 
            {% endfor %}
            {% if ns.liked %} 
            <i class="fa fa-thumbs-o-down" data-toggle="tooltip" data-placement="top" data-html="true" title="{% for person in post.likes %} {{post.getWriter(person.get_user_id())}} <br /> {% endfor %}"></i> 
            {% else %} 
            <i class="fa fa-thumbs-o-up"></i> 
            {% endif %}
             <!-- END OF likes and dislikes button -->
            <i>لایک</i>
            </a>
            <span class="float-left text-muted text-sm"> <i> {{post.comments|count()}} نظر</i> - <i> {{post.likes|count()}} لایک</i></span>
            <!-- <button id="ajaxbtn" class="btn btn-success"> ارسال ایجکسی </button> -->
        </div>
        <!-- /.card-body -->
        <div class="card-footer card-comments">
            {% for comment in comments %}
            <div class="card-comment mb-3 pr-2" style="border-right:1px solid gray">
                <!-- User image -->
                <img class="img-circle img-sm" src="{{url_for('static', filename=comment.getWriterAvatar(comment.user_id))}}">

                <div class="comment-text">
                    <span class="username">
                        {{comment.getWriter(comment.user_id)}}
                        <span class="text-muted float-left">{{moment(comment.created_at).fromNow()}}</span>
                    </span><!-- /.username -->
                    {{comment.body}}
                    {{ ckeditor.load(pkg_type="basic") }}
                    <button class="reply-link float-left text-danger text-sm btn mb-1" style="background-color: transparent;"> <i class="fa fa-reply"></i> پاسخ </button>
                    <form class="form-horizontal mt-2" style="display: none;" action="{{url_for('blog.reply_comment', post_id=post.id, comment_id=comment.id)}}" method="post" novalidate>
                        <div class="input-group input-group-sm mb-0">
                            <input class="form-control form-control-sm" name="reply" placeholder="نظر خود را در مورد این کامنت تایپ کنید">
                            <div class="input-group-append">
                              <button type="submit" class="btn btn-danger">ارسال</button>
                            </div>
                          </div>
                    </form>
                    <!-- show replies of any comment -->
                    {% for reply in comment.replies %}
                    <div class="card-comment mt-3 text-sm p-2">
                        <img class="img-circle img-sm" src="{{url_for('static', filename=reply.getWriterAvatar(comment.user_id))}}">
                        <div class="comment-text">
                            <span class="username">
                                {{reply.getWriter(reply.user_id)}}
                                <span class="text-muted float-left">{{moment(reply.created_at).fromNow()}}</span>
                            </span>
                            <div>{{reply.body}}</div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- end of replires of any comment -->
                </div>
                <!-- /.comment-text -->
            </div>
            <!-- /.card-comment -->
            {% endfor %}
        </div>
        <!-- /.card-footer -->

        <div class="card-footer">
            <form action="{{url_for('blog.comment_send', post_id=post.id)}}" method="post" novalidate>
                <!-- <img class="img-fluid img-circle img-sm" src="{{url_for('static', filename=current_user.avatar)}}"> -->
                <div class="img-push input-group">
                    {{comment_form.body(class='form-control form-control-sm col-sm-11', placeholder="نظر خود را تایپ و ثبت کنید")}}
                    <!-- <input type="text" class="form-control form-control-sm col-sm-11" placeholder="نظر خود را تایپ و ثبت کنید"> -->
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-info">ارسال</button>
                    </div>
                    <!-- <button type="submit" class="form-control form-control-sm btn btn-success col-sm-1">ارسال</button> -->
                </div>
            </form>
        </div>
        <!-- /.card-footer -->
    </div>
    <!-- /.card -->
    
</div>

{{ ckeditor.config(name='content') }}

{% endblock %}

templates/blog/post-writer.html
{% extends 'admin/index.html' %}

{% block title %} خبرهای  {{user.name}} {% endblock %}

{% block admin_content %}

<div class="offset-md-2 col-md-8">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{url_for('blog.posts')}}">اخبار</a></li>
                        <li class="breadcrumb-item active"><span>نویسنده : </span><span>{{user.name}}</span></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    {% for post in post_user %}
    <div class="card card-widget">
        <div class="card-header">
            <div class="user-block">
                <img class="img-circle" src="{{url_for('static', filename=user.avatar)}}" alt="User Image">
                <span class="username"><a href="{{url_for('blog.post_detail', post_id=post.id)}}">{{post.title}}</a></span>
                <span class="description">{{moment(post.updated_at).fromNow(refresh=True)}} به اشتراک گذاشته شد</span>
            </div>
            <!-- /.user-block -->
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-toggle="tooltip" title=""
                    data-original-title="Mark as read">
                    <i class="fa fa-circle-o"></i></button>
                <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body row">
            <img class="img-fluid pad col-md-4" src="{{url_for('static', filename=post.image)}}" width="200" alt="Attachment Image">
            <p class="card-body col-md-8">{{post.content|truncate(300)}}</p>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/blog/posts.html
{% extends 'admin/index.html' %}

{% block title %} لیست خبرها {% endblock %}

{% block admin_content %}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-header">
                    <h3 class="card-title"> لیست خبرها </h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div id="example1_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-4 col-md-4">
                                <div class="input-group dataTables_filter">
                                    <input type="search" class="form-control form-control-sm" placeholder="جستجو در جدول" aria-label="Search" aria-describedby="search-addon" />
                                    <button id="search-button" type="button" class="btn btn-primary">
                                        <i class="fa fa-search"></i>
                                      </button>
                                </div>
                            </div>                    
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example1" class="table table-bordered table-striped mt-2">
                                    <thead>
                                        <tr class="text-center">
                                            <th> ردیف </th>
                                            <th> عنوان </th>
                                            <th>متن خبر</th>
                                            <th> نویسنده </th>
                                            <th>تعداد بازدید</th>
                                            <th> تاریخ ایجاد </th>
                                            <th>وضعیت انتشار</th>
                                            <th>عملیات</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for post in posts.items %}
                                        <tr class="text-center">
                                            <td>{{loop.index}}</td>
                                            <td><a href="{{url_for('blog.post_detail', post_id=post.id)}}">{{post.title}}</a></td>
                                            <td>{{post.content|truncate(30)}}</td>
                                            <td>{{post.getWriter(post.user_id)}}</td>
                                            <td>{{post.views}}</td>
                                            <td>{{ post.created_at.strftime('%Y-%m-%d') }}</td>
                                            <td>
                                                <div class="btn-group">
                                                <a href="{{url_for('blog.post_publish', post_id=post.id)}}"
                                                    class="btn btn-sm btn-success {% if post.publish %} disabled {% endif %}"><span>منتشر</span></a>
                                                <a href="{{url_for('blog.post_publish', post_id=post.id)}}"
                                                    class="btn btn-sm btn-danger {% if not post.publish %} disabled {% endif %}"><span>پیش نویس</span></a>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="btn-group">
                                                    <a href="{{url_for('blog.post_edit', post_id=post.id)}}"
                                                        class="btn btn-sm btn-warning">ویرایش</a>
                                                    
                                                    <a href="{{url_for('blog.post_delete', post_id=post.id)}}"
                                                        class="btn btn-sm btn-danger">حذف</a>
                                                    
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-5"></div>
                            <div class="col-sm-12 col-md-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                    <ul class="pagination">
                                        {% if posts.has_prev %}
                                        <li class="paginate_button page-item previous disabled" id="example1_previous">
                                            <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0"
                                                class="page-link">قبلی</a>
                                        </li>
                                        {% endif %}
                                        {% for page_number in posts.iter_pages() %}
                                            {% if page_number %}
                                                <li class="paginate_button page-item">
                                                    <a href="{{url_for('blog.posts', page=page_number)}}"
                                                        aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                                                    {{page_number}}
                                                    </a>
                                                </li>
                                            {% else %}
                                                <li class="paginate_button page-item">
                                                    <a href="#"
                                                        aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">
                                                    {{page_number}}
                                                    </a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if posts.has_next %}
                                        <li class="paginate_button page-item next" id="example1_next">
                                            <a href="{{url_for('blog.posts', page=posts.next_num)}}"
                                                aria-controls="example1" data-dt-idx="7" tabindex="0"
                                                class="page-link">بعدی</a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->

            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->


{% endblock %}